### ISSUE TITLE
Unable to get Window authentication due to 500 server error

### ISSUE THREAD

**Issue by Iamguy84** [artisticcheese/ContainerWindowsAuth#2]
Hi folks,

I have completed enabling integrated windows authentication in windows docker container and it was successful.
[https://artisticcheese.wordpress.com/2017/09/09/enabling-integrated-windows-authentication-in-windows-docker-container/
](url)

Now I am following Asp.net core and integrated windows authentication in nanoserver container.
[https://artisticcheese.wordpress.com/2017/09/10/asp-net-core-and-integrated-windows-authentication-in-nanoserver-container/
](url)

I run cmd as fellow:
`> docker build -t mypptest . (Successfully built)`
and 
`> docker run -d -p 88:80 -h gmsa --security-opt "credentialspec=file://winauth.json" myapptest  (Successfully)`

I go to http://localhost:88/home/LocalUsers or http://10.11.22.215:88/home/LocalUsers (My IP address). **I am getting error message in the browser and it says :**

> Server Error
> 500 - Internal server error.
> There is a problem with the resource you are looking for, and it cannot be displayed.

I am using windows container and Asp.net core 2.2 or latest version.

**Docker version:**
Docker Version:
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:39:49 2019
  OS/Arch:          windows/amd64
  Experimental:     false

**Docker file (Updated):**
```
# Image with NET CORE installation to extract executables for final image
FROM microsoft/dotnet:2.2-aspnetcore-runtime-nanoserver-1803 AS CoreBuild

# Image with SDK to build .NET Core application from source
FROM microsoft/dotnet:2.2-sdk-nanoserver-1803 AS builder
WORKDIR /source/
COPY . .
RUN dotnet build
RUN dotnet publish -c Release

# Middleware image used to extract ASP.NET core module
From microsoft/iis as WindowsBuild
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';"]
# Installing NET CORE webhosting in middleware image so latest module and configuration schema is extracted for final image
ADD https://download.microsoft.com/download/B/1/D/B1D7D5BF-3920-47AA-94BD-7A6E48822F18/DotNetCore.2.0.0-WindowsHosting.exe ".\hosting.exe"
RUN start-process -Filepath .\hosting.exe -ArgumentList @('/install', '/quiet', '/norestart') -Wait 

FROM microsoft/iis:nanoserver
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';"]
RUN start-process -Filepath dism.exe -ArgumentList  @('/online', '/enable-feature:IIS-WindowsAuthentication', '/ALL') -Wait  
# Adding NET CORE EXE to Path environment variable
RUN setx /M PATH $($Env:PATH + ';' + $Env:ProgramFiles + '\dotnet')
#Copy dotnet core installation from middleware image
COPY --from=CoreBuild ["c:\\Program Files\\dotnet", "c:\\program files\\dotnet"]
#Copy dotnet core module from middleware image
COPY --from=WindowsBuild ["c:\\Windows\\System32\\inetsrv\\aspnetcore.dll", "c:\\Windows\\System32\\inetsrv\\"]
COPY --from=WindowsBuild ["c:\\Windows\\System32\\inetsrv\\config\\schema\\aspnetcore_schema.xml",  "c:\\Windows\\System32\\inetsrv\\config\\schema\\"]
WORKDIR app
# Configure IIS to use ASPNET core module
RUN Import-Module IISAdministration; `
    Start-IISCommitDelay; `
    (Get-IISServerManager).GetApplicationHostConfiguration().RootSectionGroup.Sections.Add('appSettings') ; `
    (Get-IISServerManager).GetApplicationHostConfiguration().GetSection('system.webServer/handlers').Overridemode = 'Allow' ; `
    (Get-IISServerManager).GetApplicationHostConfiguration().RootSectionGroup.SectionGroups['system.webServer'].Sections.Add('aspNetCore'); `
    (Get-IISServerManager).GetApplicationHostConfiguration().RootSectionGroup.SectionGroups['system.webServer'].Sections['aspNetCore'].OverrideModeDefault = 'Allow'; `
    New-IISConfigCollectionElement (Get-IISConfigSection 'system.webServer/globalModules' | Get-IISConfigCollection) -ConfigAttribute @{'name'='AspNetCoreModule';'image'='C:\windows\system32\inetsrv\aspnetcore.dll'}; `
    New-IISConfigCollectionElement (Get-IISConfigSection 'system.webServer/modules' | Get-IISConfigCollection) -ConfigAttribute @{'name'='AspNetCoreModule'}; `
    Stop-IISCommitDelay
# Add local user for testing authentication against local SAM database
#RUN  new-LocalUser -Name "ContainerAdmin" -Password  (ConvertTo-SecureString  "A123456!" -AsPlainText -Force); `
     #Add-LocalGroupMember -Group Administrators -Member "ContainerAdmin" ; 
# Dot net core Application to show logged on user
RUN Import-Module IISAdministration; Start-IISCommitDelay; (Get-IISServerManager).ApplicationPools['DefaultAppPool'].ProcessModel.IdentityType='LocalSystem'; `
    (Get-IISServerManager).Sites[0].Applications[0].VirtualDirectories[0].PhysicalPath = 'c:\app'; (Get-IISConfigSection -SectionPath 'system.webServer/security/authentication/windowsAuthentication').Attributes['enabled'].value = $true; `
    Stop-IISCommitDelay
# Copying compiled file from middleware NET CORE builder SDK image 
COPY --from=builder /source/bin/Release/netcoreapp2.2/publish .
EXPOSE 80 
```

Could you please resolve this issue?

Thanks in advance.

**Comment by artisticcheese** [comment]
Did you try just using existing image `artisticchese\winauth:nano-iis`, is it failing as well?

**Comment by AdnanSalah84** [comment]
Yes I tried existing image artisticcheese/winauth:nano-iis and no issue.

**Comment by Iamguy84** [comment]
Yes I tried exiting image artisticchese\winauth:nano-iis or artisticcheese/winauth:servercore and there is no issue.

**Comment by artisticcheese** [comment]
SO not sure what you are asking then. Those are images build from dockerfile above, if they work for you then entire solution is working

**Comment by Iamguy84** [comment]
```
# Installing NET CORE webhosting in middleware image so latest module and configuration schema is extracted for final image
ADD https://download.microsoft.com/download/B/1/D/B1D7D5BF-3920-47AA-94BD-7A6E48822F18/DotNetCore.2.0.0-WindowsHosting.exe ".\hosting.exe"
```
How can I get URL Windows Hosting 2.2 version?

**Comment by artisticcheese** [comment]
I used Fiddler to find it, this question shall be posted to .NET core team I imagine

**Comment by Iamguy84** [comment]
Yup I found it. I downloaded your source code as dotnet core 2.0.0. It is working well.
But dotnet core 2.2.0 or latest version is not working!

**Comment by artisticcheese** [comment]
You'd have to troubleshoot yourself. I don't really work with windows containers much anymore. Try to launch it without GMSA account and see if you get HTTP 500. It has probably nothing to do with GMSA but with .NET core webhosting in IIS container.

**Comment by Iamguy84** [comment]
Found it!

[https://github.com/aspnet/AspNetCore/issues/13861#issuecomment-530622176](url)

The issue has been fixed!
